name: quiz_app
description: A quiz application with Flutter and BLoC pattern
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.7.0

  firebase_storage: ^12.0.0



  # Images (compatible web avec limitations)
  image_picker: ^1.0.7
  image_picker_web: ^3.1.1  # Support web

  # Audio (compatible web)
  audioplayers: ^5.2.1

  # UI
  cached_network_image: ^3.3.1

  # Utilities
  uuid: ^4.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/